# Font
font_family      monospace
font_size        13.0

# Cursor
cursor_shape beam
cursor_blink_interval 0

# Scrollback
scrollback_lines 10000

# Window
enabled_layouts       tall
remember_window_size  yes
initial_window_width  120c
initial_window_height 40c
window_padding_width  4
window_margin_width   2
window_border_width   2.0pt
inactive_text_alpha   0.6
active_border_color   #95c990
inactive_border_color #4d4d4d

# Bell
enable_audio_bell no
visual_bell_duration 0

# Theme
include current-theme.conf
background_opacity 0.95

# Tabs
tab_bar_style separator
tab_separator " | "
tab_bar_edge top

# Shell
shell /usr/bin/zsh
shell_integration enabled
