[tools]
python = "latest"
node = "lts"
bun = "latest"
go = "latest"
gh = "latest"
"aws-cli" = "latest"
gcloud = "latest"
terraform = "latest"
s5cmd = "latest"
duckdb = "latest"
uv = "latest"
k9s = "latest"
lazygit = "latest"
lazydocker = "latest"
yazi = "latest"
"process-compose" = "latest"
fzf = "latest"
just = "latest"
bottom = "latest"
jq = "latest"
neovim = "latest"
